### ISSUE TITLE
unable to pull the helm archive

### ISSUE THREAD

**Issue by jconallen** [IBM/helm101#23]
It seems the reference in the index.yaml:
```
https://ibm.github.io/helm101/guestbook-0.2.0.tgz
```
returns with a 404 error.  Should the link be: 
```
https://ibm.github.io/helm101/repo/stable/guestbook-0.2.0.tgz
```

**Comment by hickeyma** [comment]
@jconallen thanks for finding this bug. I will provide a fix asap.
