### ISSUE TITLE
Broken links in Lab4

### ISSUE THREAD

**Issue by spzala** [IBM/helm101#29]
There seems few broken links in the Lab 4  
./tutorial/Lab4/README.md: Can't load url: https://github.com/helm/helm/blob/master/docs/chart_repository.md
./tutorial/Lab4/README.md: Can't load url: https://github.com/helm/helm/blob/master/docs/helm/helm_serve.md
./tutorial/README.md: Can't load url: https://github.com/helm/helm/blob/master/docs/chart_repository.md
/cc @hickeyma

**Comment by hickeyma** [comment]
Thanks for catching this @spzala. The docs framework changed during Helm v3 development and now reside in different repo and branches for both versions of Helm. The links need updating to the new web links.

I have pushed PR #30 to fix this.
